namespace ULSAlgorithms.CuttingPlanes;

/// <summary>Identifies a family of valid inequalities generated by a separator.</summary>
public enum CutFamily
{
    /// <summary>No family has been specified.</summary>
    Unknown = 0,

    /// <summary>The uncapacitated lot-sizing (l,S) inequality family.</summary>
    Ls = 1
}
