using System.Globalization;
using System.Reflection;
using System.Text;
using ULSAlgorithms.Catalog;

namespace ULSAlgorithms.PublicApiExporter;

internal static class Program
{
    private const string BootstrapMarker =
        "# BOOTSTRAP_REQUIRED";

    public static int Main(string[] args)
    {
        if (args.Length != 2)
        {
            return Usage();
        }

        var mode = args[0];
        var path = Path.GetFullPath(args[1]);

        return mode switch
        {
            "--write" => Write(path),
            "--check" => Check(path),
            _ => Usage()
        };
    }

    private static int Write(string path)
    {
        Directory.CreateDirectory(
            Path.GetDirectoryName(path) ??
            throw new InvalidOperationException(
                "Public API path has no parent directory."));

        File.WriteAllText(
            path,
            BuildSnapshot(),
            new UTF8Encoding(
                encoderShouldEmitUTF8Identifier: false));

        Console.WriteLine(
            $"Public API baseline written: {path}");
        return 0;
    }

    private static int Check(string path)
    {
        if (!File.Exists(path))
        {
            Console.Error.WriteLine(
                $"Public API baseline is missing: {path}");
            return 2;
        }

        var baselineText =
            File.ReadAllText(
                path,
                Encoding.UTF8);

        if (baselineText.Contains(
                BootstrapMarker,
                StringComparison.Ordinal))
        {
            Console.Error.WriteLine(
                "The public API baseline is still in bootstrap mode.");
            Console.Error.WriteLine(
                "Run tools/Update-PublicApiSnapshot.ps1 once and review the generated baseline.");
            return 3;
        }

        var baseline =
            ParseContractLines(
                baselineText);

        var currentText =
            BuildSnapshot();

        var current =
            ParseContractLines(
                currentText);

        var missing =
            baseline
                .Where(line => !current.Contains(line))
                .OrderBy(line => line, StringComparer.Ordinal)
                .ToArray();

        if (missing.Length != 0)
        {
            Console.Error.WriteLine(
                "Public API compatibility validation failed.");
            Console.Error.WriteLine(
                "The following baseline contracts are missing:");
            foreach (var line in missing)
            {
                Console.Error.WriteLine(
                    $"  {line}");
            }

            return 4;
        }

        Console.WriteLine(
            $"Public API compatibility validated: {baseline.Count} baseline contracts; " +
            $"{current.Count - baseline.Count} compatible additions.");
        return 0;
    }

    private static SortedSet<string> ParseContractLines(
        string text)
    {
        var result =
            new SortedSet<string>(
                StringComparer.Ordinal);

        foreach (var rawLine in text.Replace(
                     "\r\n",
                     "\n",
                     StringComparison.Ordinal).Split('\n'))
        {
            var line =
                rawLine.Trim();

            if (line.Length == 0 ||
                line.StartsWith(
                    '#'))
            {
                continue;
            }

            result.Add(line);
        }

        return result;
    }

    private static string BuildSnapshot()
    {
        var contracts =
            new SortedSet<string>(
                StringComparer.Ordinal);

        foreach (var descriptor in
                 UlsSolverCatalog.All)
        {
            contracts.Add(
                $"solver-id {descriptor.Id} => " +
                $"{descriptor.ImplementationType.FullName}");
        }

        AddConfigurationSchemaContracts(
            contracts);

        var assembly =
            typeof(UlsSolverFactory).Assembly;

        foreach (var type in
                 assembly
                     .GetExportedTypes()
                     .OrderBy(
                         type => type.FullName ?? type.Name,
                         StringComparer.Ordinal))
        {
            AddType(
                contracts,
                type);
        }

        var builder =
            new StringBuilder();

        builder.AppendLine(
            "# ULSAlgorithms public API compatibility baseline");
        builder.AppendLine(
            "# Generated by tools/ULSAlgorithms.PublicApiExporter.");
        builder.AppendLine(
            "# Existing non-comment lines must remain present; compatible additions are allowed.");
        builder.AppendLine();

        foreach (var contract in contracts)
        {
            builder.AppendLine(
                contract);
        }

        return builder.ToString();
    }

    private static void AddConfigurationSchemaContracts(
        ISet<string> contracts)
    {
        contracts.Add(
            $"config-schema {UlsSolverConfiguration.CurrentSchemaVersion}");

        var assembly =
            typeof(UlsSolverConfiguration).Assembly;

        var configurationTypes =
            new[]
            {
                typeof(UlsSolverConfiguration),
                typeof(UlsSolverCreationOptions),
                assembly.GetType(
                    "ULSAlgorithms.Optimization.Execution.LinearModelSolveOptions",
                    throwOnError: true)
                    ?? throw new InvalidOperationException(
                        "LinearModelSolveOptions type was not found."),
                assembly.GetType(
                    "ULSAlgorithms.CuttingPlanes.LsCuttingPlaneOptions",
                    throwOnError: true)
                    ?? throw new InvalidOperationException(
                        "LsCuttingPlaneOptions type was not found.")
            };

        foreach (var type in configurationTypes)
        {
            foreach (var property in
                     type.GetProperties(
                         BindingFlags.Public |
                         BindingFlags.Instance |
                         BindingFlags.DeclaredOnly)
                         .Where(
                             property =>
                                 property.GetGetMethod(
                                     nonPublic: false) is not null &&
                                 property.GetSetMethod(
                                     nonPublic: false) is not null)
                         .OrderBy(
                             property => property.Name,
                             StringComparer.Ordinal))
            {
                contracts.Add(
                    $"config-json {TypeName(type)}." +
                    $"{JsonPropertyName(property.Name)} : " +
                    $"{TypeName(property.PropertyType)}");
            }
        }
    }

    private static string JsonPropertyName(
        string propertyName)
    {
        if (propertyName.Length == 0)
        {
            return propertyName;
        }

        if (propertyName.Length == 1)
        {
            return propertyName.ToLowerInvariant();
        }

        return char.ToLowerInvariant(
                   propertyName[0]) +
               propertyName[1..];
    }

    private static void AddType(
        ISet<string> contracts,
        Type type)
    {
        contracts.Add(
            $"type {TypeKind(type)} {TypeName(type)}");

        if (type.IsEnum)
        {
            foreach (var name in Enum.GetNames(type))
            {
                var value =
                    Convert.ToInt64(
                        Enum.Parse(
                            type,
                            name),
                        CultureInfo.InvariantCulture);

                contracts.Add(
                    $"enum {TypeName(type)}.{name} = {value}");
            }
        }

        const BindingFlags flags =
            BindingFlags.Public |
            BindingFlags.Instance |
            BindingFlags.Static |
            BindingFlags.DeclaredOnly;

        foreach (var constructor in
                 type.GetConstructors(flags)
                     .OrderBy(
                         Signature,
                         StringComparer.Ordinal))
        {
            contracts.Add(
                $"ctor {TypeName(type)}{Parameters(constructor.GetParameters())}");
        }

        foreach (var property in
                 type.GetProperties(flags)
                     .OrderBy(
                         property => property.Name,
                         StringComparer.Ordinal))
        {
            var getter =
                property.GetGetMethod(
                    nonPublic: false);

            var setter =
                property.GetSetMethod(
                    nonPublic: false);

            var accessors =
                getter is not null && setter is not null
                    ? "get; set;"
                    : getter is not null
                        ? "get;"
                        : setter is not null
                            ? "set;"
                            : string.Empty;

            contracts.Add(
                $"property {Static(getter ?? setter)}" +
                $"{TypeName(property.PropertyType)} " +
                $"{TypeName(type)}.{property.Name}" +
                $"{Parameters(property.GetIndexParameters())} " +
                $"{{ {accessors} }}");
        }

        foreach (var field in
                 type.GetFields(flags)
                     .OrderBy(
                         field => field.Name,
                         StringComparer.Ordinal))
        {
            contracts.Add(
                $"field {Static(field)}" +
                $"{TypeName(field.FieldType)} " +
                $"{TypeName(type)}.{field.Name}" +
                Constant(field));
        }

        foreach (var eventInfo in
                 type.GetEvents(flags)
                     .OrderBy(
                         eventInfo => eventInfo.Name,
                         StringComparer.Ordinal))
        {
            contracts.Add(
                $"event {TypeName(eventInfo.EventHandlerType ?? typeof(void))} " +
                $"{TypeName(type)}.{eventInfo.Name}");
        }

        foreach (var method in
                 type.GetMethods(flags)
                     .Where(
                         method => !method.IsSpecialName)
                     .OrderBy(
                         Signature,
                         StringComparer.Ordinal))
        {
            var generic =
                method.IsGenericMethodDefinition
                    ? $"<{string.Join(",", method.GetGenericArguments().Select(argument => argument.Name))}>"
                    : string.Empty;

            contracts.Add(
                $"method {Static(method)}" +
                $"{TypeName(method.ReturnType)} " +
                $"{TypeName(type)}.{method.Name}{generic}" +
                $"{Parameters(method.GetParameters())}");
        }
    }

    private static string TypeKind(
        Type type)
    {
        if (type.IsEnum)
        {
            return "enum";
        }

        if (type.BaseType is not null &&
            typeof(MulticastDelegate).IsAssignableFrom(type.BaseType))
        {
            return "delegate";
        }

        if (type.IsInterface)
        {
            return "interface";
        }

        if (type.IsValueType)
        {
            return "struct";
        }

        return "class";
    }

    private static string TypeName(
        Type type)
    {
        if (type.IsByRef)
        {
            return TypeName(
                type.GetElementType() ??
                throw new InvalidOperationException(
                    "By-ref type has no element type."));
        }

        if (type.IsArray)
        {
            return TypeName(
                       type.GetElementType() ??
                       throw new InvalidOperationException(
                           "Array type has no element type.")) +
                   "[]";
        }

        var nullable =
            Nullable.GetUnderlyingType(
                type);

        if (nullable is not null)
        {
            return TypeName(
                       nullable) +
                   "?";
        }

        if (type.IsGenericParameter)
        {
            return type.Name;
        }

        if (!type.IsGenericType)
        {
            return type.FullName ??
                   type.Name;
        }

        var definition =
            type.GetGenericTypeDefinition();

        var name =
            definition.FullName ??
            definition.Name;

        var tick =
            name.IndexOf(
                '`');

        if (tick >= 0)
        {
            name =
                name[..tick];
        }

        return name +
               "<" +
               string.Join(
                   ",",
                   type.GetGenericArguments()
                       .Select(TypeName)) +
               ">";
    }

    private static string Parameters(
        ParameterInfo[] parameters) =>
        "(" +
        string.Join(
            ", ",
            parameters.Select(
                Parameter)) +
        ")";

    private static string Parameter(
        ParameterInfo parameter)
    {
        var modifier =
            parameter.IsOut
                ? "out "
                : parameter.ParameterType.IsByRef
                    ? parameter.IsIn
                        ? "in "
                        : "ref "
                    : string.Empty;

        var optional =
            parameter.IsOptional
                ? $" = {DefaultValue(parameter.DefaultValue)}"
                : string.Empty;

        return modifier +
               TypeName(
                   parameter.ParameterType) +
               " " +
               parameter.Name +
               optional;
    }

    private static string DefaultValue(
        object? value)
    {
        if (value is null ||
            value == DBNull.Value ||
            value == Missing.Value)
        {
            return "null";
        }

        return value switch
        {
            string text =>
                "\"" +
                text.Replace(
                    "\"",
                    "\\\"",
                    StringComparison.Ordinal) +
                "\"",
            char character =>
                "'" +
                character +
                "'",
            bool boolean =>
                boolean
                    ? "true"
                    : "false",
            Enum enumValue =>
                enumValue.ToString(),
            IFormattable formattable =>
                formattable.ToString(
                    null,
                    CultureInfo.InvariantCulture) ??
                value.ToString() ??
                string.Empty,
            _ =>
                value.ToString() ??
                string.Empty
        };
    }

    private static string Constant(
        FieldInfo field)
    {
        if (!field.IsLiteral)
        {
            return string.Empty;
        }

        return " = " +
               DefaultValue(
                   field.GetRawConstantValue());
    }

    private static string Static(
        MethodBase? method) =>
        method?.IsStatic == true
            ? "static "
            : string.Empty;

    private static string Static(
        FieldInfo field) =>
        field.IsStatic
            ? "static "
            : string.Empty;

    private static string Signature(
        MethodBase method) =>
        method.Name +
        Parameters(
            method.GetParameters());

    private static int Usage()
    {
        Console.Error.WriteLine(
            "Usage: ULSAlgorithms.PublicApiExporter " +
            "[--write <path> | --check <path>]");
        return 1;
    }
}
