using System.Reflection;

namespace ULSAlgorithms;

/// <summary>
/// Exposes stable runtime metadata for the ULSAlgorithms assembly.
/// </summary>
/// <remarks>
/// This type is intentionally infrastructure-only. No ULS model or algorithm is
/// introduced in the 0.1.0 bootstrap release.
/// </remarks>
public static class ULSAlgorithmsInfo
{
    private static readonly Assembly CurrentAssembly = typeof(ULSAlgorithmsInfo).Assembly;

    /// <summary>
    /// Gets the assembly name.
    /// </summary>
    public static string Name => CurrentAssembly.GetName().Name ?? "ULSAlgorithms";

    /// <summary>
    /// Gets the CLR assembly version.
    /// </summary>
    public static Version Version =>
        CurrentAssembly.GetName().Version ?? new Version(0, 0, 0, 0);

    /// <summary>
    /// Gets the informational version generated by the repository versioning infrastructure.
    /// </summary>
    public static string InformationalVersion =>
        CurrentAssembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
            ?.InformationalVersion
        ?? Version.ToString();
}
